#!/bin/bash
#SBATCH --job-name=kpsc_exp_dl
#SBATCH --output=/home/lshlt19/CNVRock/logs/exp_dl_%A_%a.out
#SBATCH --error=/home/lshlt19/CNVRock/logs/exp_dl_%A_%a.err
#SBATCH --time=06:00:00
#SBATCH --mem=12G
#SBATCH --cpus-per-task=4
#SBATCH --partition=normal
#SBATCH --array=1-5000%50   # overridden at submission time

# Download + align Phase 2 KpSC expansion samples (88,135 new samples).
#
# Reads from assets/ena_url_manifest.tsv (built by build_ena_url_manifest.py).
# Uses HTTPS (not FTP) to avoid firewall blocks.
# Handles both PAIRED and SINGLE library layouts.
#
# Prerequisites:
#   1. Build URL manifest first:
#        python3 data/setup/build_ena_url_manifest.py
#   2. BAM directory exists: data/raw/bam/
#
# Usage (wave-based — do NOT submit all at once due to MaxJobCount=10000):
#   Run via ~/bam_wave_submit.sh (auto-generated by this script's companion).
#   Or manually, one chunk at a time:
#     BATCH_OFFSET=0 sbatch --array=1-100%100 hpc/download_expansion_sra.sh

set -euo pipefail

REPO_DIR="/home/lshlt19/CNVRock"
export PATH="/home/lshlt19/miniconda3/envs/cnvrock/bin:/home/lshlt19/miniconda3/bin:$PATH"

module load bwa/0.718
module load samtools/1.20

MANIFEST="$REPO_DIR/assets/ena_url_manifest.tsv"
REFERENCE="$REPO_DIR/assets/HS11286_extended.fasta"
FASTQ_TMP="$REPO_DIR/data/raw/fastq"
BAM_DIR="$REPO_DIR/data/raw/bam"

mkdir -p "$FASTQ_TMP" "$BAM_DIR" "$REPO_DIR/logs"

# BATCH_OFFSET allows wave-based submission (100-task chunks, no dependency chains)
LINE_NUM=$(( ${BATCH_OFFSET:-0} + SLURM_ARRAY_TASK_ID + 1 ))  # +1 to skip header

ROW=$(sed -n "${LINE_NUM}p" "$MANIFEST")
if [[ -z "$ROW" ]]; then
    echo "No row for task $SLURM_ARRAY_TASK_ID (line $LINE_NUM) — skipping."
    exit 0
fi

ACC=$(echo    "$ROW" | cut -f1)
LAYOUT=$(echo "$ROW" | cut -f2)
R1_URL=$(echo "$ROW" | cut -f3)
R2_URL=$(echo "$ROW" | cut -f4)

BAM_OUT="$BAM_DIR/${ACC}.bam"
if [[ -f "$BAM_OUT" && -f "$BAM_OUT.bai" ]]; then
    echo "$ACC already done — skipping."
    printf '%s\t%s\n' "$ACC" "$BAM_OUT" \
        >> "$REPO_DIR/assets/kpsc_expansion_paths_to_bams.tsv.partial"
    exit 0
fi

if [[ -z "$R1_URL" ]]; then
    echo "ERROR: no URL for $ACC in manifest — skipping." >&2
    exit 1
fi

echo "Task $SLURM_ARRAY_TASK_ID: $ACC  (layout=$LAYOUT)"

# ── Download FASTQs via HTTPS ─────────────────────────────────────────────────
download_file() {
    local URL="$1" DST="$2"
    local ATTEMPT=0
    while [[ $ATTEMPT -lt 3 ]]; do
        if wget -q --timeout=300 --tries=1 "$URL" -O "$DST"; then
            [[ -s "$DST" ]] && return 0
        fi
        ATTEMPT=$(( ATTEMPT + 1 ))
        echo "  wget attempt $ATTEMPT failed for $URL; retrying in 30 s …"
        rm -f "$DST"
        sleep 30
    done
    echo "ERROR: failed to download $URL" >&2
    return 1
}

R1="$FASTQ_TMP/${ACC}_1.fastq.gz"
R2="$FASTQ_TMP/${ACC}_2.fastq.gz"

download_file "$R1_URL" "$R1"

if [[ "$LAYOUT" == "PAIRED" && -n "$R2_URL" ]]; then
    download_file "$R2_URL" "$R2"
fi

# ── Align to extended reference ───────────────────────────────────────────────
if [[ "$LAYOUT" == "PAIRED" && -f "$R2" && -s "$R2" ]]; then
    bwa mem -t "$SLURM_CPUS_PER_TASK" \
        -R "@RG\tID:${ACC}\tSM:${ACC}\tPL:ILLUMINA" \
        "$REFERENCE" "$R1" "$R2" \
        | samtools sort -@ "$SLURM_CPUS_PER_TASK" -o "$BAM_OUT"
else
    # Single-end alignment
    echo "  Aligning single-end reads for $ACC"
    bwa mem -t "$SLURM_CPUS_PER_TASK" \
        -R "@RG\tID:${ACC}\tSM:${ACC}\tPL:ILLUMINA" \
        "$REFERENCE" "$R1" \
        | samtools sort -@ "$SLURM_CPUS_PER_TASK" -o "$BAM_OUT"
fi

samtools index "$BAM_OUT"

rm -f "$R1" "$R2"

printf '%s\t%s\n' "$ACC" "$BAM_OUT" \
    >> "$REPO_DIR/assets/kpsc_expansion_paths_to_bams.tsv.partial"

echo "Done: $ACC → $BAM_OUT"
